using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Numerics;
using System.Reflection.PortableExecutable;
using System.Text;
using System.Threading.Tasks;
using static System.Net.Mime.MediaTypeNames;
using System.Xml;

namespace DAlertsApi.Models.ApiV1
{
    /// <summary>
    /// id:             The unique custom alert identifier
    /// external_id:    Unique alert ID generated by the application developer.Or null if ID was not provided
    /// header:         Text that will be displayed as a header. Or null if text was not provided
    /// message:        Text that will be displayed inside the message box. Or null if text was not provided
    /// image_url:      URL to the image file that will displayed along with the custom alert. Or null if URL was not provided
    /// sound_url:      URL to the sound file that will played when displaying the custom alert. Or null if URL was not provided
    /// is_shown:       A flag indicating whether the alert was shown in the streamer's widget
    /// created_at:     The date and time (YYYY-MM-DD HH.MM.SS formatted) when custom alert was created
    /// shown_at:       Date and time indicating when the alert was shown(YYYY-MM-DD HH.MM.SS formatted). Or null if the alert is not shown yet
    /// </summary>
    public class CustomAlertsResponse
    {
        public int Id { get; set; }
        public string? External_id { get; set; }
        public string? Header { get; set; }
        public string? Message { get; set; }
        public string? Image_url { get; set; }
        public string? Sound_url { get; set; }
        public int Is_show { get; set; }
        public string Created_at { get; set; } = string.Empty;
        public string? Shown_at { get; set; } 
    }

    public class CustomAlertsResponseWrap
    {
        public CustomAlertsResponse Data { get; set; } = new();
    }
}
