using Newtonsoft.Json;

namespace DAlertsApi.Models.ApiV1.Alerts
{
    /// <summary>
    /// Sends custom alert to the authorized user. Requires user authorization with the oauth-custom_alert-store scope. 
    /// POST:           https://www.donationalerts.com/api/v1/custom_alert
    /// 
    /// curl \
    /// -X POST https://www.donationalerts.com/api/v1/custom_alert \
    /// -H "Authorization: Bearer <token>" \
    /// -H "Content-Type: application/x-www-form-urlencoded" \
    /// -d "external_id=12&header=Custom%20header&message=Custom%20message&image_url=https%3A%2F%2Fcdn.frankerfacez.com%2Femoticon%2F408827%2F4"
    /// 
    /// External_id:    Up to 32 characters long unique alert ID generated by the application developer
    /// Header:         Up to 255 characters long string that will be displayed as a header
    /// Message:        Up to 300 characters long string that will be displayed inside the message box
    /// Is_shown:       A value containing 0 or 1. Determines whether the alert should be displayed or not.Default value: 0
    /// Image_url:      Up to 255 characters long URL to the image file that will displayed along with the custom alert
    /// Sound_url:      Up to 255 characters long URL to the sound file that will played when displaying the custom alert
    /// </summary>
    public class CustomAlertsRequest
    {
        public string External_id { get; set; } = string.Empty;
        public string Header { get; set; } = string.Empty;
        public string Message { get; set; } = string.Empty;
        public int Is_show { get; set; }
        public string Image_url { get; set; } = string.Empty;
        public string Sound_url { get; set; } = string.Empty;

        public override string ToString() => JsonConvert.SerializeObject(this);
    }
}
